"""Original reader guides with explicit research provenance and useful next steps."""
import html
from pathlib import Path
from build_guides import parse, md
ROOT=Path(__file__).resolve().parent.parent
SLUGS=('before-a-used-car-viewing','what-car-photos-cannot-tell-you','recalls-history-and-inspections','fuel-economy-label-to-your-budget','seller-promise-to-written-evidence','complaint-counts-without-failure-rates')
def visual(slug):
 if slug=='fuel-economy-label-to-your-budget':
  return '<figure class="guide-visual"><figcaption><strong>Same distance. Different fuel bill.</strong> Illustrative inputs: 12,000 miles/year, $3.50 per US gallon.</figcaption><svg viewBox="0 0 600 180" role="img" aria-label="Illustrative annual fuel costs: 30 US MPG costs 1400 dollars; 40 US MPG costs 1050 dollars."><text x="15" y="37">30 US MPG</text><rect x="155" y="17" width="360" height="44" rx="8" fill="#12685e"/><text x="170" y="46" fill="white">$1,400 / year</text><text x="15" y="109">40 US MPG</text><rect x="155" y="89" width="270" height="44" rx="8" fill="#925b27"/><text x="170" y="118" fill="white">$1,050 / year</text></svg><div class="table-wrap"><table><caption>Arithmetic behind the example</caption><thead><tr><th>Economy</th><th>Gallons/year</th><th>Fuel/year</th></tr></thead><tbody><tr><td>30 US MPG</td><td>400</td><td>$1,400</td></tr><tr><td>40 US MPG</td><td>300</td><td>$1,050</td></tr></tbody></table></div><p class="note">Difference: $350/year for fuel only. This is a fictional scenario, not the total cost of either car. See the assumptions and break-even discussion below.</p></figure>'
 if slug=='seller-promise-to-written-evidence':
  return '<figure class="guide-visual"><figcaption><strong>Turn reassurance into specific questions.</strong></figcaption><ol class="guide-diagram"><li><b>What was said?</b><span>Record the actual issue and the proposed work.</span></li><li><b>What is agreed?</b><span>Clarify scope, timing, responsibility and the written documents.</span></li><li><b>What is supported?</b><span>Review work records with an independent inspector; follow up on gaps.</span></li></ol><p class="note">An original question framework based on the FTC guidance linked below. It does not certify repair quality or determine your contractual rights.</p></figure>'
 if slug=='complaint-counts-without-failure-rates':
  return '<figure class="guide-visual"><figcaption><strong>A report count has limits.</strong></figcaption><div class="guide-diagram"><section><b>Reported signal</b><p>Dated complaint records for a stated vehicle identity.</p></section><section><b>Still missing</b><p>Verified failures, comparable exposure and the condition of your candidate.</p></section><section><b>Useful next step</b><p>Read the concern, confirm version scope and ask for inspection and service evidence.</p></section></div><p class="note">Qualitative explanation of record limits, not a statistical reliability chart. Source: NHTSA dataset documentation and MotorJury methodology linked below.</p></figure>'
 return ''

def main(write):
 cards=[]
 for slug in SLUGS:
  meta,body=parse((ROOT/'data/guides'/f'{slug}.md').read_text())
  text=md(body,lambda _: '')
  article=f'<section class="collection-hero compact"><p class="eyebrow">A practical reader guide · checked {meta["date"]}</p><h1>{html.escape(meta["title"])}</h1><p class="lede">{html.escape(meta["description"])}</p></section><article class="collection-story">{visual(slug)}{text}<p class="note">Published by MotorJury. AI-assisted desk research and original editorial suggestions. No vehicle test or specialist review is claimed.</p></article><section class="card"><h2>Keep exploring</h2><a href="/guides/">All reviewed reader guides →</a> · <a href="/ask/">Ask a question about this guide</a></section>'
  write('/guides/'+slug+'/',meta['title'],article,description=meta['description'],og_type='article',jsonld=[{'@context':'https://schema.org','@type':'Article','headline':meta['title'],'description':meta['description'],'url':'https://motorjury.com/guides/'+slug+'/','dateModified':meta['date'],'author':{'@type':'Organization','name':'MotorJury'},'publisher':{'@type':'Organization','name':'MotorJury'},'mainEntityOfPage':'https://motorjury.com/guides/'+slug+'/'}])
  cards.append(f'<article class="card"><h2><a href="/guides/{slug}/">{html.escape(meta["title"])}</a></h2><p>{html.escape(meta["description"])}</p></article>')
 write('/guides/','Guides that help you take the next step','<section class="collection-hero compact"><p class="eyebrow">Read, ask, prepare</p><h1>Make your next car question a useful one.</h1><p class="lede">Practical guides for a viewing, a photo comparison or a closer look at the evidence.</p></section><div class="guide-cards">'+''.join(cards)+'</div><section class="card"><h2>Considering a US RAV4?</h2><p>Work through the version, manufacturer records, seller questions and your own costs.</p><a href="/buying-brief/">2019–2020 RAV4 buying brief →</a> · <a href="/guides/rav4-gasoline-vs-hybrid/">Gasoline and Hybrid: compare your costs</a></section><section class="card"><h2>Here for the cars?</h2><p>Follow six engineering ideas through our collection.</p><a href="/discover/">Explore the design stories →</a></section>')
