import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {HubDO} from './hub.js';
import {dashboardDispatch,digest,passwordHash,validateTask,validateMetric} from './dashboard-store.mjs';
import {handleDashboard} from './dashboard.mjs';
import BASE from './dashboard-data.json' with {type:'json'};
function hub(){const db=new DatabaseSync(':memory:');const sql={exec(q,...args){const s=db.prepare(q);const rows=s.columns().length?s.all(...args):(s.run(...args),[]);return {toArray:()=>rows};}};return new HubDO({storage:{sql}});}
async function configured(){const h=hub();const token='unit-test-provisioning-token';assert.deepEqual(await dashboardDispatch(h,'dashboard-setup',{token,password:'test-only-password'},await digest(token)),{ok:true});return h;}
async function login(h){const r=await dashboardDispatch(h,'dashboard-login',{password:'test-only-password',ip:'127.0.0.1'});assert.ok(r.token);return r.token;}
const valid={id:'TEST-01',title:'Verify a task',area:'Operations',owner:'Test',priority:1,status:'verified',acceptance:'Evidence passes',evidence:'Test result',verified_at:'2026-10-07'};
test('provisioning refuses an incorrect high-entropy token',async()=>{const h=hub();const r=await dashboardDispatch(h,'dashboard-setup',{token:'bad',password:'test-only-password'});assert.equal(r.status,403);assert.equal(h.one('SELECT COUNT(*) n FROM dashboard_config').n,0);});
test('provisioning cannot replace an existing password',async()=>{const h=await configured();assert.equal((await dashboardDispatch(h,'dashboard-setup',{token:'bad',password:'replace-password'})).status,409);});
test('password stored only as a salted verifier',async()=>{const h=await configured();const raw=h.one("SELECT v FROM dashboard_config WHERE k='credentials'").v;assert.ok(!raw.includes('test-only-password'));const c=JSON.parse(raw);assert.equal(c.hash.length,64);assert.equal(c.salt.length,64);assert.equal(await passwordHash('test-only-password',c.salt),c.hash);});
test('wrong password is rejected and repeated guesses are bounded',async()=>{const h=await configured();for(let i=0;i<5;i++)assert.equal((await dashboardDispatch(h,'dashboard-login',{password:'incorrect',ip:'guessing'})).status,401);assert.equal((await dashboardDispatch(h,'dashboard-login',{password:'test-only-password',ip:'guessing'})).status,429);});
test('raw session tokens are not stored; revoked tokens are rejected',async()=>{const h=await configured(),token=await login(h);assert.equal(h.one('SELECT hash FROM dashboard_sessions').hash,await digest(token));assert.ok((await dashboardDispatch(h,'dashboard-session',{token})).ok);await dashboardDispatch(h,'dashboard-logout',{token});assert.equal((await dashboardDispatch(h,'dashboard-state',{token})).status,401);});
test('expired sessions cannot read or modify records',async()=>{const h=await configured(),token=await login(h);h.sql.exec('UPDATE dashboard_sessions SET expires=?',Date.now()-1);assert.equal((await dashboardDispatch(h,'dashboard-task',{token,task:valid})).status,401);});
test('tasks need completion evidence and a date',()=>{assert.throws(()=>validateTask({...valid,evidence:''}));assert.throws(()=>validateTask({...valid,verified_at:'2099-01-01'}));assert.throws(()=>validateTask({...valid,priority:9}));assert.equal(validateTask(valid).status,'verified');});
test('task edits persist and retain a history trail',async()=>{const h=await configured(),token=await login(h);await dashboardDispatch(h,'dashboard-task',{token,task:valid});const state=await dashboardDispatch(h,'dashboard-state',{token});assert.equal(state.tasks['TEST-01'].title,valid.title);assert.equal(state.history.length,1);assert.equal(state.history[0].kind,'task');});
test('unknown, impossible and unscoped metric values cannot become measurements',()=>{const m={id:'return_rate',value:12,start:'2026-08-01',end:'2026-08-31',source:'Test cohort report'};assert.equal(validateMetric(m,['return_rate']).value,12);for(const extra of [{value:''},{value:101},{source:''},{end:'2099-01-01'},{start:'2026-09-01'},{id:'unknown'}])assert.throws(()=>validateMetric({...m,...extra},['return_rate']));});
test('zero is a real entered measurement while missing metrics remain absent',async()=>{const h=await configured(),token=await login(h);await dashboardDispatch(h,'dashboard-metric',{token,metric_ids:['organic_clicks'],metric:{id:'organic_clicks',value:0,start:'2026-08-01',end:'2026-08-31',source:'Test export'}});const state=await dashboardDispatch(h,'dashboard-state',{token});assert.equal(state.metrics.organic_clicks.value,0);assert.equal(state.metrics.net_contribution,undefined);});
function env(h){return {HUB:{idFromName:()=>0,get:()=>({fetch:req=>h.fetch(req)})},ASSETS:{fetch:async()=>new Response('',{status:200})}};}
const req=(path,body,origin='https://motorjury.com',cookie='')=>new Request('https://motorjury.com'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},...(body?{body:JSON.stringify(body)}:{})});
test('anonymous data and app requests never return dashboard records',async()=>{const h=await configured(),e=env(h);for(const path of ['/api/dashboard/data','/api/dashboard/tasks','/dashboard/app.js']){const r=await handleDashboard(req(path),new URL('https://motorjury.com'+path),e);assert.equal(r.status,401);assert.ok(!(await r.text()).includes('historical_audit'));}const page=await handleDashboard(req('/dashboard'),new URL('https://motorjury.com/dashboard'),e);assert.ok((await page.text()).includes('type="password"'));assert.match(page.headers.get('X-Robots-Tag'),/noindex/);assert.match(page.headers.get('Cache-Control'),/no-store/);});
test('cross-origin login and writes are rejected',async()=>{const h=await configured(),e=env(h);for(const path of ['/api/dashboard/login','/api/dashboard/tasks','/api/dashboard/setup']){const r=await handleDashboard(req(path,{password:'test-only-password'},'https://attacker.example'),new URL('https://motorjury.com'+path),e);assert.equal(r.status,403);}});
test('successful login uses a secure HTTP-only cookie, never a JSON token',async()=>{const h=await configured(),e=env(h),r=await handleDashboard(req('/api/dashboard/login',{password:'test-only-password'}),new URL('https://motorjury.com/api/dashboard/login'),e);assert.equal(r.status,200);assert.deepEqual(await r.json(),{ok:true});assert.match(r.headers.get('Set-Cookie'),/__Host-mj_dashboard=.*HttpOnly; Secure; SameSite=Strict/);});
test('registry preserves all current task IDs, named old findings and original archive rows',()=>{assert.equal(new Set(BASE.tasks.map(t=>t.id)).size,BASE.tasks.length);assert.equal(BASE.archive.length,57);assert.equal(BASE.historical_audit.reported_findings,24);assert.equal(BASE.historical_audit.named_findings_in_supplied_text,15);for(const id of ['DATA-01','DATA-04','MOB-01','IA-01','SEO-01','SEO-02','DATA-02','DATA-03','MONEY-01','CONTENT-01','I18N-01','UX-03','SEC-01','PHOTO-04','LEGAL-01'])assert.ok(BASE.tasks.some(t=>t.id===id));});
